// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function app() {
  return ReasonReact.element(/* None */0, /* None */0, Home.make("Home", /* array */[]));
}

exports.app = app;
/* Home Not a pure module */
