// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.js");
var Random = require("bs-platform/lib/js/random.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

Random.self_init(/* () */0);

function app() {
  return ReasonReact.element(/* None */0, /* None */0, Home.make("Home", /* array */[]));
}

exports.app = app;
/*  Not a pure module */
