// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var TextInput$BsReactNative = require("bs-react-native/lib/js/src/components/textInput.js");
var TouchableOpacity$BsReactNative = require("bs-react-native/lib/js/src/components/touchableOpacity.js");

var component = ReasonReact.statelessComponent("EditButton");

function make(value, isEditing, onEdit, onSwitch, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      if (isEditing !== 0) {
        return ReasonReact.element(/* None */0, /* None */0, TextInput$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                                Style$BsReactNative.textAlign(/* Center */3),
                                /* :: */[
                                  Style$BsReactNative.backgroundColor("#DDD"),
                                  /* :: */[
                                    Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
                                    /* :: */[
                                      Style$BsReactNative.width(/* Pt */Block.__(0, [300])),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[onEdit], /* None */0, /* Some */[(function () {
                              return Curry._1(onSwitch, /* false */0);
                            })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[value], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]));
      } else {
        return ReasonReact.element(/* None */0, /* None */0, TouchableOpacity$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                                Style$BsReactNative.alignItems(/* Center */2),
                                /* :: */[
                                  Style$BsReactNative.backgroundColor("#AAA"),
                                  /* :: */[
                                    Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
                                    /* :: */[
                                      Style$BsReactNative.width(/* Pt */Block.__(0, [300])),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ])], /* None */0, /* Some */[(function () {
                              return Curry._1(onSwitch, /* true */1);
                            })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[value]))]));
      }
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
