// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var TodoCell = require("./TodoCell.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Alert$BsReactNative = require("bs-react-native/lib/js/src/alert.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Button$BsReactNative = require("bs-react-native/lib/js/src/components/button.js");
var FlatList$BsReactNative = require("bs-react-native/lib/js/src/components/flatList.js");

function onButtonPress(v) {
  return Alert$BsReactNative.alert("你好，" + (String(v) + ""), /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);
}

var component = ReasonReact.reducerComponent("Home");

function renderItem(onPress) {
  return (function (param) {
      return FlatList$BsReactNative.renderItem((function (param) {
                    var item = param[/* item */0];
                    return ReasonReact.element(/* None */0, /* None */0, TodoCell.make(item[/* text */1], item[/* finish */2], (function (b) {
                                      return Curry._1(onPress, /* record */[
                                                  /* key */item[/* key */0],
                                                  /* text */item[/* text */1],
                                                  /* finish */b
                                                ]);
                                    }), /* array */[]));
                  }), param);
    });
}

function make(name, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                              Style$BsReactNative.flex(1),
                              /* :: */[
                                Style$BsReactNative.justifyContent(/* Center */2),
                                /* :: */[
                                  Style$BsReactNative.alignItems(/* Center */2),
                                  /* [] */0
                                ]
                              ]
                            ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                      ReasonReact.element(/* None */0, /* None */0, TodoCell.make(name, self[/* state */2][/* toggle */1], (function (b) {
                                  return Curry._1(self[/* send */4], /* ElseToggle */Block.__(2, [b]));
                                }), /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Button$BsReactNative.make(/* None */0, /* Some */["#841584"], /* None */0, /* Some */[(function () {
                                      return Curry._1(self[/* send */4], /* UpserTask */Block.__(0, [/* record */[
                                                      /* key */Pervasives.string_of_int(List.length(self[/* state */2][/* tasks */0])),
                                                      /* text */"hieegh key: " + Pervasives.string_of_int(List.length(self[/* state */2][/* tasks */0])),
                                                      /* finish : false */0
                                                    ]]));
                                    })], /* None */0, /* Some */["Learefaefaeoeeere"])(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, FlatList$BsReactNative.make($$Array.of_list(self[/* state */2][/* tasks */0]), renderItem((function (item) {
                                        return Curry._1(self[/* send */4], /* Toggle */Block.__(1, [item]));
                                      })), (function (item, _) {
                                    return item[/* key */0];
                                  }), /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]))
                    ]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* tasks : [] */0,
              /* toggle : false */0
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      switch (action.tag | 0) {
        case 0 : 
            return /* Update */Block.__(0, [/* record */[
                        /* tasks : :: */[
                          action[0],
                          state[/* tasks */0]
                        ],
                        /* toggle */state[/* toggle */1]
                      ]]);
        case 1 : 
            var i = action[0];
            return /* Update */Block.__(0, [/* record */[
                        /* tasks : :: */[
                          i,
                          List.filter((function (x) {
                                    return +(x[/* key */0] !== i[/* key */0]);
                                  }))(state[/* tasks */0])
                        ],
                        /* toggle */state[/* toggle */1]
                      ]]);
        case 2 : 
            return /* Update */Block.__(0, [/* record */[
                        /* tasks : [] */0,
                        /* toggle */action[0]
                      ]]);
        
      }
    });
  return newrecord;
}

exports.onButtonPress = onButtonPress;
exports.component = component;
exports.renderItem = renderItem;
exports.make = make;
/* component Not a pure module */
