// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Random = require("bs-platform/lib/js/random.js");
var TodoCell = require("./TodoCell.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Alert$BsReactNative = require("bs-react-native/lib/js/src/alert.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Button$BsReactNative = require("bs-react-native/lib/js/src/components/button.js");
var FlatList$BsReactNative = require("bs-react-native/lib/js/src/components/flatList.js");
var StatusBar$BsReactNative = require("bs-react-native/lib/js/src/components/statusBar.js");
var Dimensions$BsReactNative = require("bs-react-native/lib/js/src/dimensions.js");

var windowWidth = Dimensions$BsReactNative.get(/* window */-762539024).width;

function onButtonPress(v) {
  return Alert$BsReactNative.alert("你好，" + (String(v) + ""), /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);
}

var component = ReasonReact.reducerComponent("Home");

function renderItem(onPress, onDelete, onEdit) {
  return (function (param) {
      return FlatList$BsReactNative.renderItem((function (param) {
                    var item = param[/* item */0];
                    return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                                            Style$BsReactNative.flex(1),
                                            /* :: */[
                                              Style$BsReactNative.borderBottomWidth(0.5),
                                              /* :: */[
                                                Style$BsReactNative.borderColor("#222"),
                                                /* :: */[
                                                  Style$BsReactNative.width(/* Pt */Block.__(0, [windowWidth])),
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, TodoCell.make(item[/* text */1], item[/* finish */3], (function (b) {
                                                return Curry._1(onPress, /* record */[
                                                            /* key */item[/* key */0],
                                                            /* text */item[/* text */1],
                                                            /* order */item[/* order */2],
                                                            /* finish */b
                                                          ]);
                                              }), (function () {
                                                return Curry._1(onDelete, item);
                                              }), (function (s) {
                                                return Curry._1(onEdit, /* record */[
                                                            /* key */item[/* key */0],
                                                            /* text */s,
                                                            /* order */item[/* order */2],
                                                            /* finish */item[/* finish */3]
                                                          ]);
                                              }), /* array */[]))]));
                  }), param);
    });
}

function make(title, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                              Style$BsReactNative.flex(1),
                              /* :: */[
                                Style$BsReactNative.justifyContent(/* Center */2),
                                /* :: */[
                                  Style$BsReactNative.alignItems(/* Center */2),
                                  /* :: */[
                                    Style$BsReactNative.backgroundColor("#444"),
                                    /* :: */[
                                      Style$BsReactNative.width(/* Pt */Block.__(0, [windowWidth])),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                      ReasonReact.element(/* None */0, /* None */0, StatusBar$BsReactNative.make(/* None */0, /* Some */[/* lightContent */-106329341], /* Some */[/* false */0], /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(0.13),
                                        /* :: */[
                                          Style$BsReactNative.flexDirection(/* ColumnReverse */3),
                                          /* :: */[
                                            Style$BsReactNative.width(/* Pt */Block.__(0, [windowWidth])),
                                            /* [] */0
                                          ]
                                        ]
                                      ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                                                  Style$BsReactNative.flexDirection(/* Row */0),
                                                  /* :: */[
                                                    Style$BsReactNative.justifyContent(/* SpaceBetween */5),
                                                    /* [] */0
                                                  ]
                                                ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                                          ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[title])),
                                          ReasonReact.element(/* None */0, /* None */0, Button$BsReactNative.make(/* None */0, /* Some */["#f08080"], /* None */0, /* Some */[(function () {
                                                          return Curry._1(self[/* send */4], /* UpserTask */Block.__(0, [/* record */[
                                                                          /* key */Pervasives.string_of_int(Random.$$int(100000)),
                                                                          /* text */"My task",
                                                                          /* order */List.length(self[/* state */2][/* tasks */0]),
                                                                          /* finish : false */0
                                                                        ]]));
                                                        })], /* None */0, /* Some */["Add +"])(/* array */[]))
                                        ]))])),
                      ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(0.78),
                                        /* :: */[
                                          Style$BsReactNative.flexDirection(/* Column */2),
                                          /* :: */[
                                            Style$BsReactNative.justifyContent(/* Center */2),
                                            /* :: */[
                                              Style$BsReactNative.alignItems(/* Center */2),
                                              /* :: */[
                                                Style$BsReactNative.backgroundColor("#EEE"),
                                                /* :: */[
                                                  Style$BsReactNative.width(/* Pt */Block.__(0, [windowWidth])),
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, FlatList$BsReactNative.make($$Array.of_list(List.sort((function (x, y) {
                                                      return x[/* order */2] - y[/* order */2] | 0;
                                                    }), self[/* state */2][/* tasks */0])), renderItem((function (item) {
                                                  return Curry._1(self[/* send */4], /* UpserTask */Block.__(0, [item]));
                                                }), (function (item) {
                                                  return Curry._1(self[/* send */4], /* DeleteTask */Block.__(1, [item]));
                                                }), (function (item) {
                                                  return Curry._1(self[/* send */4], /* UpserTask */Block.__(0, [item]));
                                                })), (function (item, _) {
                                              return item[/* key */0];
                                            }), /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]))])),
                      ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(0.09),
                                        /* :: */[
                                          Style$BsReactNative.width(/* Pt */Block.__(0, [windowWidth])),
                                          /* [] */0
                                        ]
                                      ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Footerrrr"]))]))]))
                    ]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* tasks : [] */0,
              /* toggle : false */0
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      switch (action.tag | 0) {
        case 0 : 
            var i = action[0];
            return /* Update */Block.__(0, [/* record */[
                        /* tasks : :: */[
                          i,
                          List.filter((function (x) {
                                    return +(x[/* key */0] !== i[/* key */0]);
                                  }))(state[/* tasks */0])
                        ],
                        /* toggle */state[/* toggle */1]
                      ]]);
        case 1 : 
            var i$1 = action[0];
            return /* Update */Block.__(0, [/* record */[
                        /* tasks */List.filter((function (x) {
                                  return +(x[/* key */0] !== i$1[/* key */0]);
                                }))(state[/* tasks */0]),
                        /* toggle */state[/* toggle */1]
                      ]]);
        case 2 : 
            return /* Update */Block.__(0, [/* record */[
                        /* tasks : [] */0,
                        /* toggle */action[0]
                      ]]);
        
      }
    });
  return newrecord;
}

exports.windowWidth = windowWidth;
exports.onButtonPress = onButtonPress;
exports.component = component;
exports.renderItem = renderItem;
exports.make = make;
/* windowWidth Not a pure module */
