// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var EditButton = require("./EditButton.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Button$BsReactNative = require("bs-react-native/lib/js/src/components/button.js");
var Switch$BsReactNative = require("bs-react-native/lib/js/src/components/switch.js");

var component = ReasonReact.reducerComponent("TodoCell");

function make(value, toggle, onToggle, onDelete, onEdit, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                      ReasonReact.element(/* None */0, /* None */0, EditButton.make(value, self[/* state */2], onEdit, (function (b) {
                                  return Curry._1(self[/* send */4], /* ToggleEdit */[b]);
                                }), /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[Pervasives.string_of_bool(toggle)])),
                      ReasonReact.element(/* None */0, /* None */0, Button$BsReactNative.make(/* None */0, /* Some */["#f08080"], /* None */0, /* Some */[(function () {
                                      return Curry._1(onDelete, /* () */0);
                                    })], /* None */0, /* Some */["delete"])(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Switch$BsReactNative.make(/* None */0, /* None */0, /* Some */[onToggle], /* None */0, /* None */0, /* Some */[toggle], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]))
                    ]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* false */0;
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [action[0]]);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
